[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
goerli = "${GOERLI_RPC}"
polygon = "${POLYGON_MAINNET_RPC}"
mumbai = "${MUMBAI_RPC}"
moonbeam = "${MOONBEAM_MAINNET_RPC}"
moonbase = "${MOONBASE_RPC}"
arbitrum_one = "${ARBITRUM_RPC}"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
ignored_error_codes = ["license"]
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
mainnet = { key = "${ETHERSCAN_TOKEN}" }
goerli = { key = "${ETHERSCAN_TOKEN}" }
polygon = { key = "${POLYGONSCAN_TOKEN}" }
mumbai = { key = "${POLYGONSCAN_TOKEN}" }
moonbeam = { key = "${MOONSCAN_TOKEN}" }
moonbase = { key = "${MOONSCAN_TOKEN}" }
arbitrum_one = { key = "${ARBISCAN_TOKEN}", chain = "arbitrum" }

[profile.mainnet_libs]
libraries = [
    "src/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0xac82748a93cc98e6e9a36fff80f4e1bc40ca573f",
    "src/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0xe283911bbb6454a1a1442410d12d5f33df88daa0",
    "src/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x4b17e8da6a9138ff0b0ccd2eb2e1279646e3dfc8",
    "src/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x1d225d6975f77f2e9ff1f37fde85ebd752743c33",
    "src/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0x4c04e52328c84022a24e89458628a3ef45bcd3b5",
    "src/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x5ff675d0ea4a0fa5fad769b1b76060bf58d4ced4",
]

[profile.arbitrum_one_libs]
libraries = [
    "src/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0xAb3A01fcc9E7A596e94EC98A488ddC22e6067904",
    "src/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0xcBE1d19d6AE9e4707aa5F104c395a33DfaeC6f9d",
    "src/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x7F6455c71Fb95912C2E265dC21b6132ae37ebFb8",
    "src/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x20925520877Ed05b2c1E0115c6d1c9807B34a0c6",
    "src/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0x38D99A1e6BC87C6343c7C626bcf27B7b8dDC3392",
    "src/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0xc62e8d922f00Dcf246a88c40E84de5da496F5b88",
]