[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
goerli = "${GOERLI_RPC}"
polygon = "${POLYGON_MAINNET_RPC}"
mumbai = "${MUMBAI_RPC}"
moonbeam = "${MOONBEAM_MAINNET_RPC}"
moonbase = "${MOONBASE_RPC}"
arbitrum_one = "${ARBITRUM_RPC}"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
ignored_error_codes = ["license"]
evm_version = "paris"

[invariant]
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
mainnet = { key = "${ETHERSCAN_TOKEN}" }
goerli = { key = "${ETHERSCAN_TOKEN}" }
polygon = { key = "${POLYGONSCAN_TOKEN}" }
mumbai = { key = "${POLYGONSCAN_TOKEN}" }
moonbeam = { key = "${MOONSCAN_TOKEN}" }
moonbase = { key = "${MOONSCAN_TOKEN}" }
arbitrum_one = { key = "${ARBISCAN_TOKEN}", chain = "arbitrum" }
sepolia = { key = "${ETHERSCAN_TOKEN}" }

[profile.mainnet_libs]
libraries = [
    "src/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0xac82748a93cc98e6e9a36fff80f4e1bc40ca573f",
    "src/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0xe283911bbb6454a1a1442410d12d5f33df88daa0",
    "src/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x4b17e8da6a9138ff0b0ccd2eb2e1279646e3dfc8",
    "src/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x1d225d6975f77f2e9ff1f37fde85ebd752743c33",
    "src/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0x4c04e52328c84022a24e89458628a3ef45bcd3b5",
    "src/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x5ff675d0ea4a0fa5fad769b1b76060bf58d4ced4",
]

[profile.arbitrum_one_libs]
libraries = [
    "src/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0xAb3A01fcc9E7A596e94EC98A488ddC22e6067904",
    "src/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0xcBE1d19d6AE9e4707aa5F104c395a33DfaeC6f9d",
    "src/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x7F6455c71Fb95912C2E265dC21b6132ae37ebFb8",
    "src/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x5Fc33C7732FcECb364a28278cD12d8137FFB90Cb",
    "src/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0x38D99A1e6BC87C6343c7C626bcf27B7b8dDC3392",
    "src/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0xc62e8d922f00Dcf246a88c40E84de5da496F5b88",
]

[profile.polygon_libs]
libraries = [
    "src/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0x4bD51179f30Cd162167D40AF9F6d378FC580C9cd",
    "src/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0xC29CEEfe88a1eD4384a1BaD42592e70a3E3b0B86",
    "src/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x65E5Ed385C62A786e61Dd863053dE04a24CB627e",
    "src/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0xaD289BC22E12E4744AE6896c0812A60EE4e04A65",
    "src/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0xd6f13c8dd1509e6fB5cfBc8194132977c31b7c3D",
    "src/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x28219423FdA748495E10DFa05F089233A5491e16",
]